Crear componente Card para mostrar en listados Fix/ot165 60
alkemyTech/OT165-Angular-client pull request #36
Opened 2022-03-23 23:54 UTC by lorenzo0895

### **Resumen**
- Editado componente Card, ahora puede presionarse para navegar a otra página.
- Se modificó la ubicación del componente Logo, se lo colocó dentro de la carpeta /shared/components

2022-03-24 14:22 UTC, anagon88 requested changes

2022-03-24 14:22 UTC, anagon88 commented on src/app/shared/components/card/card.component.ts
> +  @Input() href: string = '/';
no me gusta el nombre href, tiene que ser mas descriptivo porque peuden haber varios href en el component

2022-03-25 18:56 UTC, lorenzo0895 commented on src/app/shared/components/card/card.component.ts
> +  @Input() href: string = '/';
Editado por detailsLink. También se agregaron los cambios de isTable.

2022-03-25 19:32 UTC, anagon88 approved these changes

2022-03-25 20:06 UTC, anagon88 approved these changes

2022-03-25 20:11 UTC, merged