Feat/ot165 29
alkemyTech/OT165-Angular-client pull request #39
Opened 2022-03-25 14:03 UTC by efernandezdev

**Resume**

 Add reusable form to edit and create activity.
Add  upload image inside ./assets.
Require name and image fields.
Only .jpg and .png extensions.

View /backoffice/actividades to create a new activity:

![actividadesCreate](https://user-images.githubusercontent.com/86627778/160134717-49fe1cf1-df9b-4ca4-b679-fb6135e912d2.jpg)
![actividadesCreate1](https://user-images.githubusercontent.com/86627778/160134723-229bc33d-8c79-4ec1-8f20-1407931aa2c4.jpg)

View /backoffice/actividades/:id

![actividadesEdit](https://user-images.githubusercontent.com/86627778/160134947-cf98bf6f-f92b-4518-83ca-f3952203bcdc.jpg)
![actividadesEdit1](https://user-images.githubusercontent.com/86627778/160134951-44c1fc4b-f32c-46c5-8ea3-c3587fd18c1b.jpg)

2022-03-25 19:38 UTC, anagon88 requested changes

2022-03-25 19:38 UTC, anagon88 commented on src/app/backoffice/pages/activities/activity-form/activity-form.component.ts
> +    name: "Futurama",
Te falto limpiar estos valores iniciales, entiendo que fueron para las pruebas no?

2022-03-26 01:24 UTC, efernandezdev commented on src/app/backoffice/pages/activities/activity-form/activity-form.component.ts
> +    name: "Futurama",
si, para diferenciar el form Editar.

2022-03-26 21:53 UTC, anagon88 requested changes

2022-03-26 21:53 UTC, anagon88 commented on src/app/backoffice/pages/activities/activity-form/activity-form.component.ts
> +    name: "Futurama",
dejalos limpios, sin datos mockeados

2022-03-26 22:50 UTC, anagon88 approved these changes

2022-03-26 22:58 UTC, merged