Fix/ot165-111 - Actualizamos reducer de Usuarios
alkemyTech/OT165-Angular-client pull request #76
Opened 2022-04-07 14:26 UTC by DanieLazo17

**Resumen**

- Agregamos actions de actualización y creación de usuarios
- Agregamos actions, reducer, effects y selectors en el formulario de usuario

2022-04-07 21:18 UTC, anagon88 requested changes

2022-04-07 22:28 UTC, DanieLazo17 commented on src/app/backoffice/pages/users/user-form/user-form.component.ts
> +        //this.userForm.reset();
Codigo removido

2022-04-07 22:29 UTC, DanieLazo17 commented on src/app/backoffice/pages/users/user-form/user-form.component.ts
> +            name: this.userForm.get('name')?.value,
Listo

2022-04-07 22:29 UTC, DanieLazo17 commented on src/app/state/actions/users.actions.ts
> +  props<{ user: any }>()
Se agrego Interfaz

2022-04-09 02:08 UTC, anagon88 approved these changes

2022-04-09 02:08 UTC, merged