Feat/ot165 108
alkemyTech/OT165-Angular-client pull request #82
Opened 2022-04-09 03:18 UTC by efernandezdev

**Resume**

- Implemented redux with NgRx.
- created state, reducers, actions, effects and selectors.

2022-04-11 18:00 UTC, anagon88 requested changes

2022-04-11 18:00 UTC, anagon88 commented on src/app/backoffice/services/activities/activities.service.ts
> +  public updateActivity(id: number, activity: any): Observable<any> {
trata de no usar any, si necesitas crear otra entidad crealo

2022-04-11 23:30 UTC, efernandezdev commented on src/app/backoffice/services/activities/activities.service.ts
> +  public updateActivity(id: number, activity: any): Observable<any> {
corregido.

2022-04-12 02:43 UTC, anagon88 approved these changes

2022-04-12 02:43 UTC, merged