Feat/ot165 135
alkemyTech/OT165-Angular-client pull request #86
Opened 2022-04-10 22:23 UTC by efernandezdev

**Resume**

- Created routing and module for campaign landing page "juguetes por más sonrisas".
- Created header whit logo, slogan and campaign logo.
- Responsive design: movil, tablet, pc and smart tv.

**Evidence**
Movil ( logo ):

![image](https://user-images.githubusercontent.com/86627778/162642194-5cbe9def-6428-48ff-bf58-ce6bf9b431f2.png)

Tablet (logo and campaign logo):

![image](https://user-images.githubusercontent.com/86627778/162642234-4aa5bfcd-3ee4-4b7d-a4cc-596d0fda895d.png)

Pc (logo, slogan and campaign logo):

![image](https://user-images.githubusercontent.com/86627778/162642249-b11cf1d7-9a84-4ba2-a654-7eb257cd48d4.png)

Smart tv( logo, slogan, campaign logo and background header whit opacity):

![image](https://user-images.githubusercontent.com/86627778/162642269-bbe2bc68-c4ca-4dc7-92c3-dc081c6034f1.png)

2022-04-11 18:14 UTC, anagon88 requested changes

2022-04-11 18:14 UTC, anagon88 commented on src/app/landing/campana-juguetes/campana-juguetes-routing.module.ts
> +import { NgModule } from "@angular/core";
cambiar el nombre a ingles porque todos los nomrbes son en ingles

2022-04-11 23:32 UTC, efernandezdev commented on src/app/landing/campana-juguetes/campana-juguetes-routing.module.ts
> +import { NgModule } from "@angular/core";
corregido.

2022-04-12 02:43 UTC, anagon88 approved these changes

2022-04-12 13:30 UTC, merged