OT165-132-136-mas-detalles
alkemyTech/OT165-Angular-client pull request #92
Opened 2022-04-12 20:05 UTC by nacho992

se agregó efectos de transición en algunos componentes, y se arreglaron estilos para que se vea toda la app más uniforme, se actualizó el carousel y otros componentes para que sean responsives

2022-04-13 01:35 UTC, anagon88 requested changes

2022-04-13 01:35 UTC, anagon88 commented on src/app/app.module.ts
> -    PublicModule,
esta ok eliminar este module?

2022-04-13 13:21 UTC, nacho992 commented on src/app/app.module.ts
> -    PublicModule,
si está ok, importa el PublicModule en toys.module hacía que no compile

2022-04-14 15:59 UTC, anagon88 approved these changes

2022-04-14 15:59 UTC, merged